---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: fluxcd
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:keikumata/helm-operator-get-started
    path: charts/podinfo
    ref: dev
  values:
    image:
      repository: 304154187190.dkr.ecr.us-east-1.amazonaws.com/flux/test
      tag: dev-v97efv53
    replicaCount: 1
    hpa:
      enabled: false
