---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: fluxcd
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:keikumata/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: 304154187190.dkr.ecr.us-east-1.amazonaws.com/flux/test
      tag: stg-qpi6ytpe
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
